<h1><?php echo $this->getTwitterWelcome(); ?></h1>
<p>
	<?php $this->mostrarTwitts(''); ?>
    <a class="twitter-timeline"  href="https://twitter.com/hashtag/vinos" data-widget-id="965667942816985089">Tweets sobre #vinos</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          
</p>